development:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL_SIDEKIQ") { "redis://redis:6379/12" } %>

test:
  adapter: test

production:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL_SIDEKIQ") { "redis://redis:6379/12" } %>
  channel_prefix: hyrax_production

